### ISSUE TITLE
On development of this project

### ISSUE THREAD

**Issue by wgwz** [technige/py2neo#631] opened 2017-06-06 16:48 UTC
It's obvious that you are still working on this project @technige, but it's kind of disappointing that are not many responses to the open issues. Perhaps many of the issues can be closed as simple misunderstandings. For myself, I would like to contribute but I need some guidance. I also learn a lot about a project by responses and activity in issues. I think more activity in the issues could help reduce the bus factor and be an overall benefit to the project. This is just a suggestion, as I enjoy working with this project and want to see it continue to improve

**Comment by pvanheus** [comment] 2017-06-09 06:04
I'm also interested in this topic. I'm working on a conda package for py2neo as a step towards incorporating it in [bioconda](https://bioconda.github.io/), and I notice that a bug with the py2neo shell writing to console has been fixed in the latest *v4* code (commit 9b11afd303bd05544ceacb511001101d71e79e5b). So I'm interested in how this project will move forward, when the next beta will be, etc.

BTW. the tests with `bau` don't complete for me with latest *v4* code and Python 3.5. Not sure if the problem is my side. I'm considering using Docker to build test infrastructure if anyone else is interested.

**Comment by AlJohri** [comment] 2017-06-15 16:29
seconding @wgwz's sentiment. more activity in the issues would be great!

**Comment by technige** [comment] 2017-07-07 09:08
Sorry that I haven't been able to spend much time working on this recently. As you may or may not know, this is only a personal project and spare time filler for me. I tend to use the project as a laboratory for trying stuff out and have nothing resembling a roadmap or long term plan. That makes it almost impossible to hand anything over to anyone else; I usually make up features as I go along.

But I obviously don't want to ditch the project so I've been working out how to take it forward. This thread explains a bit more...

https://twitter.com/technige/status/883248540050489344

**Comment by wgwz** [comment] 2017-07-07 15:47
For posterity here is technige's thread:

#Neo4j/py2neo thread follows... Given the success of the #Neo4j official drivers, I've been pondering the future of py2neo for a while. [1]

Pragmatically, there exists a significant amount of overlap between the two drivers and I only have limited time. [2]

Conversely, I don't want to bin the project as I enjoy writing it and so many people seem to still like it. [3]

So I've decided to do two things. One, try to bring the two projects closer together and two, spin off bits as separate projects. [4]

The first spin-off is cypy (pip install technige.cypy # http://nige.tech/cypy/ ). This is a Cypher utility library containing. [5]

comprehensive graphy data types, Cypher repr functions and a really solid new pygments lexer for Cypher. [6]

The second spin-off is n4 (pip install n4 # https://github.com/technige/n4 ). This is an interactive console and command line tool. [7]

Really pleased with this one and a huge hat-tip to the awesome @_nicolemargaret for some serious inspiration from cycli (we miss you!) [8]

The other planned spin-offs are for the OGM and calendar modules. Not started those yet but they're on the cards. [9]

That leaves the HTTP support and the classic py2neo API. I'm still considering and consulting on this but these will either be rolled [10]

into the official Python driver in some form or will survive as an extension or wrapper project. [11]

So. Despite six months of what appears like inactivity on py2neo, I have been plotting and scheming and good things are happening! FIN [12]

**Comment by wgwz** [comment] 2017-07-07 16:09
I like the idea of spinning off into separate projects. I think that makes sense, and it will make maintaining and developing the projects easier. Let's say you did do that, how would you manage the connection to the db for each project? i.e. say you spun off the OGM and the classic py2neo API. each needs a connection to the db. it would make sense to start depending on the official driver for the connection, right?

**Comment by pvanheus** [comment] 2017-07-07 16:58
Under the hood py2neo depends on the official driver for the connection already. BTW. when it comes to OGM there is also [neomodel](https://github.com/robinedwards/neomodel). @technige perhaps you can comment on whether you till see py2neo OGM as having advantages over neomodel OGM?

**Comment by wgwz** [comment] 2017-07-07 18:38
I was talking about v3. Which is what I'm using at the moment bc no new releases have been made on pypi (I believe).

**Comment by wgwz** [comment] 2017-07-07 18:41
But that's good, because it will make factoring out these projects easier I suppose.

**Comment by pvanheus** [comment] 2017-07-07 18:55
Latest version on pypi is 4.0.0b2: https://pypi.python.org/pypi/py2neo/4.0.0b2

**Comment by wgwz** [comment] 2017-07-08 00:02
I would guess the OGM and neomodel stuff should just merge (if they haven't already). But seconding @pvanheus, if you have any thoughts on that I'm also curious to hear that.

**Comment by technige** [comment] 2017-07-08 23:31
I'll try to answer some of these....

Firstly, I strongly recommend ignoring any v4 beta releases already made. These were carried out before I made a decision on which way I was taking the project and as such do not represent a path it will be useful to follow. For this reason, I've removed `4.0.0b*` from pypi and am starting again with v4 in general. Stick with the latest v3 for now until I've got a bit further.

In terms of managing the DB connection, there are two aspects to that. For Bolt, I will be using the official driver in all future versions of py2neo. For HTTP, I will be spinning out an HTTP "extension" for the official driver and using that. Most of that code will come from the current py2neo code base. Therefore, py2neo will ultimately rely on both the official driver and the HTTP extension, as well as CyPy.

The OGM and time/calendar projects will then become py2neo "extension" projects, both depending on py2neo and therefore indirectly also using the official driver.

In terms of OGM vs Neomodel, I see no conflict there. I worked with Rob on the first version of Neomodel but I haven't been close to the project for a long time. It was developed with Django in mind and I don't use (and actually strongly dislike) Django. My OGM was built from scratch and has no connection with Django. If anything, it is closer to the SQLAlchemy ORM than Django but it's not really very close to that either. I actually wanted to create an OGM API from first principles so if you find it useful, great; if not (or if you use Django) stick with Neomodel.

**Comment by wgwz** [comment] 2017-07-08 23:54
On second thought I would actually really appreciate a spin off of the py2neo OGM API. Just wanted to get on record saying that. That's what I have been using and I think there's good room for improvement there. What's been done there works nicely.  It would be a shame to have that binned and not with potential to progress.

**Comment by technige** [comment] 2018-06-05 07:59
V4 RC1 is now available. This should go GA later this week.

**Comment by technige** [comment] 2018-06-07 12:32
Yes, I decided the overhead of splitting out the projects was probably going to be too great, so I've resorted to continuing with the project as it was. `py2neo.ogm` is still available.

And with today's release of v4, I'm going to close this issue.

**Closed by technige** 2018-06-07 12:32 UTC
