### ISSUE TITLE
Saving datetime objects returns Neotime objects - OGM

### ISSUE THREAD

**Issue by Askir** [technige/py2neo#743] opened 2019-02-04 10:11 UTC
Saving a normal `datetime.datetime` Object in an OGM Object. Makes py2neo cast that object to a Neotime object to save it to the database.
When retrieving though the object is not casted back so for example:
```python
    created_at = Property()
    updated_at = Property()
   ######
   ogm_object.updated_at = datetime.datetime.now()
   graph.push(ogm_object)
   ogm_object = graph.match(...).first()
   ogm_object.updated_at.__class__ # will equal Neotime not datetime.datetime :(
```

**Comment by technige** [comment] 2019-02-07 16:14
This is expected behaviour. Neo4j uses nanosecond precision for its temporal types whereas Python only supports microsecond precision. The `neotime` module provides support for the true Neo4j types but, for convenience, the driver allows coercion _from_ Python's native temporal types. The reverse operation is not provided since (A) this would be lossy and (B) the original type information is not preserved.

**Comment by Askir** [comment] 2019-02-07 17:24
Shouldn't the ogm abstract from that fact though? The time that the datetime object has is not precise enough anyways as you said so no info is lost when converting back that would be meaningful.

**Comment by Askir** [comment] 2019-02-07 17:26
Neomodel handles datetime just fine though so ill just use that instead. Although it has its own problems it just seems like the more fleshed out neo4j integration.

**Comment by technige** [comment] 2019-04-26 13:47
Closing issue as user has flounced off to an alternative library.

**Closed by technige** 2019-04-26 13:47 UTC
