### ISSUE TITLE
ValueError: Cannot append walkable ( exception in data.py)

### ISSUE THREAD

**Issue by ilanle** [technige/py2neo#684] opened 2018-08-01 16:26 UTC
Hi guys,
py2neo 4.0.0

I am running into the following problem in some queries.
I don't know if this is because something was corrupted in the database or for any other reason.
basically I run
`graph.run(query).data()
`
In some queries, I get the following exception (or similar), however some queries do run correctly:

```
  File "/app/utils/query_graph.py", line 31, in get_general_query
    results = graph.run(query).data()
  File "/usr/local/lib/python3.6/site-packages/py2neo/database.py", line 491, in run
    return self.begin(autocommit=True).run(cypher, parameters, **kwparameters)
  File "/usr/local/lib/python3.6/site-packages/py2neo/database.py", line 851, in run
    self.finish()
  File "/usr/local/lib/python3.6/site-packages/py2neo/database.py", line 860, in finish
    self.process()
  File "/usr/local/lib/python3.6/site-packages/py2neo/database.py", line 857, in process
    self.session.sync()
  File "/usr/local/lib/python3.6/site-packages/neo4j/v1/api.py", line 357, in sync
    detail_count, _ = self._connection.sync()
  File "/usr/local/lib/python3.6/site-packages/neo4j/bolt/connection.py", line 383, in sync
    detail_delta, summary_delta = self.fetch()
  File "/usr/local/lib/python3.6/site-packages/neo4j/bolt/connection.py", line 290, in fetch
    return self._fetch()
  File "/usr/local/lib/python3.6/site-packages/neo4j/bolt/connection.py", line 313, in _fetch
    self.responses[0].on_records(details)
  File "/usr/local/lib/python3.6/site-packages/neo4j/v1/result.py", line 55, in on_records
    self._records.extend(map(lambda record: self.zipper(self.keys(), self._hydrant.hydrate(record)), records))
  File "/usr/local/lib/python3.6/site-packages/neo4j/v1/result.py", line 55, in <lambda>
    self._records.extend(map(lambda record: self.zipper(self.keys(), self._hydrant.hydrate(record)), records))
  File "/usr/local/lib/python3.6/site-packages/py2neo/internal/packstream.py", line 91, in hydrate
    return tuple(hydrate_(value, entities.get(keys[i])) for i, value in enumerate(values))
  File "/usr/local/lib/python3.6/site-packages/py2neo/internal/packstream.py", line 91, in <genexpr>
    return tuple(hydrate_(value, entities.get(keys[i])) for i, value in enumerate(values))
  File "/usr/local/lib/python3.6/site-packages/py2neo/internal/packstream.py", line 80, in hydrate_
    return Path(*steps)
  File "/usr/local/lib/python3.6/site-packages/py2neo/data.py", line 1077, in __init__
    Walkable.__init__(self, walk(*entities))
  File "/usr/local/lib/python3.6/site-packages/py2neo/data.py", line 666, in __init__
    self.__sequence = tuple(iterable)
  File "/usr/local/lib/python3.6/site-packages/py2neo/data.py", line 60, in walk
    "to node %r" % (walkable, end_node))
ValueError: Cannot append walkable (_4258558)-[:TAGGED {}]->(_8451129) to node (_8183404:WIF {class_label: 'A1', idd: '60601f9e', sbar: '3d279e'})
```

**Comment by technige** [comment] 2018-08-13 09:16
What's your query?

**Comment by technige** [comment] 2018-12-03 18:57
Closing due to tumbleweed.

**Closed by technige** 2018-12-03 18:57 UTC
Labels: not enough info, v4

**Comment by jexp** [comment] 2019-11-23 10:30
@technige I have a neo4j-users guy who runs into the same error, not sure what the root cause is.

Scoubi 03:15
I have some random crash. I can run the code a few times and it rarely crash at the same place

```
Traceback (most recent call last):
  File "BlueHound.py", line 210, in <module>
    main()
  File "BlueHound.py", line 193, in main
    getshortestpaths()
  File "BlueHound.py", line 90, in getshortestpaths
    getpaths(paths)
  File "BlueHound.py", line 72, in getpaths
    havepath = testimpact(origsnode,origenode)
  File "BlueHound.py", line 41, in testimpact
    havepath=result.evaluate()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/py2neo/database.py", line 1207, in evaluate
    if self.forward():
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/py2neo/database.py", line 1173, in forward
    new_current = fetch()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/py2neo/internal/hydration/__init__.py", line 114, in fetch
    self._on_more()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/neobolt/direct.py", line 422, in fetch
    return self._fetch()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/neobolt/direct.py", line 449, in _fetch
    self.responses[0].on_records(details)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/neobolt/direct.py", line 737, in on_records
    handler(records)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/py2neo/internal/connectors.py", line 252, in <lambda>
    cx.pull_all(on_records=lambda records: result.append_records(map(hydrator.hydrate, records)),
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/py2neo/internal/hydration/__init__.py", line 61, in append_records
    self._records.extend(tuple(record) for record in records)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/py2neo/internal/hydration/__init__.py", line 61, in <genexpr>
    self._records.extend(tuple(record) for record in records)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/py2neo/internal/hydration/__init__.py", line 220, in hydrate
    return tuple(self.hydrate_object(value, self.entities.get(self.keys[i]))
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/py2neo/internal/hydration/__init__.py", line 220, in <genexpr>
    return tuple(self.hydrate_object(value, self.entities.get(self.keys[i]))
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/py2neo/internal/hydration/__init__.py", line 233, in hydrate_object
    return self.hydrate_path(*fields)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/py2neo/internal/hydration/__init__.py", line 274, in hydrate_path
    return Path(*steps)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/py2neo/data.py", line 1078, in __init__
    Walkable.__init__(self, walk(*entities))
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/py2neo/data.py", line 669, in __init__
    self.__sequence = tuple(iterable)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/py2neo/data.py", line 59, in walk
    raise ValueError("Cannot append walkable %r "
ValueError: Cannot append walkable (COMP08532.TESTLAB.LOCAL)-[:HasSession {}]->(DAMBROSE02770@TESTLAB.LOCAL) to node (_11213:User {displayname: 'Cheri Baragar', domain: 'TESTLAB.LOCAL', enabled: true, lastlogon: 1555489842, name: 'CBARAGAR00078@TESTLAB.LOCAL', objectsid: 'S-1-5-21-883232822-274137685-4173207997-1078', owned: false, pwdlastset: -1})
Second time it went further but crashed with
ValueError: Cannot append walkable (HPLASENCIA00001@TESTLAB.LOCAL)-[:MemberOf {}]->(IT08271@TESTLAB.LOCAL) to node (_22387:Group {domain: 'TESTLAB.LOCAL', name: 'IT01254@TESTLAB.LOCAL'})
```

Scoubi 18:22
I'm starting to wonder if my connection to the DB fails sometimes. 
Anyone knows how I could catch that error? And maybe redo the query if it fails. 
It has happened to me a few time in the Python console...
Scoubi 04:04
Still have the crash. I remove the whole fonction. But still crash when I do path.evaluate()
If anyone has an idea how to prevent this I'd love to know
it is rather annoying
I'm considering using another library to interact with neo4j
Scoubi 04:40
even when I do
```
while cursor.forward():
    print(cursor.current)
```
it crashes before getting to the end :disappointed:
Michael Hunger 22:02
perhaps you should share your full code?
new messages
Scoubi 03:25
```
from py2neo import Graph, Node, Relationship
graph = Graph("bolt://localhost:7687",password="neo4jj")
domain="TESTLAB.LOCAL"
def havepath(startnode,endnode):
	query='match p=shortestpath((n {name:{snode}})-[*1..]->(m {name:{enode}})) return p'
	result=graph.run(query,snode=startnode,enode=endnode).evaluate()
def addrel(startnode,startnodetype,reltype,endnode,endnodetype):
	# This function adds back the relationship (edge) between objects after the impact of the removal have been evaluated
	query='MERGE (n:%s {name:{snode}}) WITH n MERGE (m:%s {name:{enode}}) WITH n,m MERGE (n)-[:%s]->(m)' % (startnodetype[0], endnodetype[0], reltype)
	stats=graph.run(query,snode=startnode,enode=endnode).stats()
	print("Add:",startnode,reltype,endnode)
	print(stats)
	print("")
def delrel(startnode,reltype,endnode):
	# this function delete the relationship (edge) between two obect in the graph
	query='MATCH p=((n)-[r:%s]->(m)) WHERE n.name={snode} AND m.name={enode} DELETE r' % (reltype)
	stats=graph.run(query,snode=startnode,enode=endnode).stats()
	print("DELETE:",startnode,reltype,endnode)
	print(stats)
def getreltype(startnode,endnode):
	# Get the Relationship Type between Starting Node and End Node
	# Those nodes should be only 1 hop apart
	# Return the relationship type as a string
	query='MATCH ((n)-[r]->(m)) WHERE n.name={snode} AND m.name={enode} RETURN type(r)'
	result=graph.run(query,snode=startnode,enode=endnode)
	reltype=result.evaluate()
	#result.close()
	return reltype
def getnodetype(mynode):
	query='match (n {name:{node}}) return labels(n)'
	result=graph.run(query,node=mynode)
	nodetype=result.evaluate()
	result.close()
	return nodetype
def testimpact(origsnode,origenode):
	query='MATCH p=shortestpath((n)-[*1..]->(m)) WHERE n.name={snode} AND m.name={enode} RETURN p'
	print("testimpact",origsnode,origenode)
	havepath=graph.run(query,snode=origsnode,enode=origenode).evaluate()
	#havepath=result.evaluate()
	#havepath=result.current
	#print("Impact Tested")
	return havepath
def getpaths(paths):
	# This function break down all the paths in the "paths" variable
	# For each pair of nodes it will get the relationship type, delete the relationship, 
	# evaluate the impact on the graph and add the relationship back
	# origsnode and origenode are the Original Strating and Ending Nodes of the query that called this function
	# They are used to test if there is still a path after deleting a relationship in the path
	path=paths.evaluate()
	x=0
	while path != None:
		# Loop through all the paths 
		i=0 
		origsnode=path.start_node["name"]
		origenode=path.end_node["name"]
		print(path)
		pathdestroyed=False
		while i < len(path)-1 and pathdestroyed==False:
			# No need to evaluate the last relationship of the chain as it's usually "MemberOf Domain Admins"
			# If we find a relationship that breaks the Attack Path we stop evaluting paths
			startnode=path[i].start_node["name"]
			endnode=path[i].end_node["name"]
			sntype=getnodetype(startnode)
			entype=getnodetype(endnode)
			if not endnode.startswith('DOMAIN USERS@'):
				reltype=getreltype(startnode,endnode)
				delrel(startnode,reltype,endnode)
				havepath = testimpact(origsnode,origenode)
				addrel(startnode,sntype,reltype,endnode,entype)
				if havepath == None:
					print("-------------------------------")
					print("Deleting relationship",reltype ,"between", startnode, "and", endnode, "breaks the path!")
					print("-------------------------------")
					pathdestroyed=True
				else:
					print("Path:",havepath)
			else:
				print("------")
				print(" DONT TEST MemberOf DOMAIN USERS")
				print("------")
			i+=1
		path=paths.evaluate()
		x=x+1
		print(x)
		print("")
def getshortestpaths():
	query = 'MATCH p=ShortestPath((n:User)-[*1..]->(m:Group {name:{gname}})) WHERE n <> m RETURN p'
	dadom='DOMAIN ADMINS@'+domain
	paths = graph.run(query,gname=dadom)
	print(dadom)
	getpaths(paths)
def main():
	x=True
	while x==True:
		print("1: Shortest Paths to highvalue targets")
		print("0: Exit")
		response=input("Choice: ")
		if response == "1":
			getshortestpaths()
		else:
			x=False
if __name__ == "__main__":
	main()
(edited)
Scoubi 03:39
@michael.neo If I comment the call to delrel and addrel I could go through 4k+ paths
Then I tested to comment only the call to test impact, I went almost to 1.5k before it crashed
with the whole script it crash before 100 paths
You can use this script to build a database : https://github.com/BloodHoundAD/BloodHound-Tools/blob/master/DBCreator/DBCreator.py
Scoubi 04:00
I just created a brand new DB with 500 Users, 500 Computers and 500 Groups
Here's the output when it ran (just before the crash
(MSINNETT00231@TESTLAB.LOCAL)-[:MemberOf {}]->(DOMAIN ADMINS@TESTLAB.LOCAL)
25
(DLAFOREST00235@TESTLAB.LOCAL)-[:MemberOf {}]->(IT00152@TESTLAB.LOCAL)-[:AdminTo {}]->(COMP00294.TESTLAB.LOCAL)-[:HasSession {}]->(LSCHRANDT00166@TESTLAB.LOCAL)-[:MemberOf {}]->(DOMAIN ADMINS@TESTLAB.LOCAL)
DELETE: DLAFOREST00235@TESTLAB.LOCAL MemberOf IT00152@TESTLAB.LOCAL
constraints_added: 0
constraints_removed: 0
contained_updates: True
indexes_added: 0
indexes_removed: 0
labels_added: 0
labels_removed: 0
nodes_created: 0
nodes_deleted: 0
properties_set: 0
relationships_created: 0
relationships_deleted: 1
testimpact DLAFOREST00235@TESTLAB.LOCAL DOMAIN ADMINS@TESTLAB.LOCAL
Traceback (most recent call last):
  File "sub.py", line 113, in <module>
    main()
  File "sub.py", line 109, in main
    getshortestpaths()
  File "sub.py", line 101, in getshortestpaths
    getpaths(paths)
  File "sub.py", line 69, in getpaths
    havepath = testimpact(origsnode,origenode)
  File "sub.py", line 39, in testimpact
    havepath=graph.run(query,snode=origsnode,enode=origenode).evaluate()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/py2neo/database.py", line 1207, in evaluate
    if self.forward():
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/py2neo/database.py", line 1173, in forward
    new_current = fetch()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/py2neo/internal/hydration/__init__.py", line 114, in fetch
    self._on_more()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/neobolt/direct.py", line 422, in fetch
    return self._fetch()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/neobolt/direct.py", line 449, in _fetch
    self.responses[0].on_records(details)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/neobolt/direct.py", line 737, in on_records
    handler(records)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/py2neo/internal/connectors.py", line 252, in <lambda>
    cx.pull_all(on_records=lambda records: result.append_records(map(hydrator.hydrate, records)),
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/py2neo/internal/hydration/__init__.py", line 61, in append_records
    self._records.extend(tuple(record) for record in records)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/py2neo/internal/hydration/__init__.py", line 61, in <genexpr>
    self._records.extend(tuple(record) for record in records)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/py2neo/internal/hydration/__init__.py", line 220, in hydrate
    return tuple(self.hydrate_object(value, self.entities.get(self.keys[i]))
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/py2neo/internal/hydration/__init__.py", line 220, in <genexpr>
    return tuple(self.hydrate_object(value, self.entities.get(self.keys[i]))
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/py2neo/internal/hydration/__init__.py", line 233, in hydrate_object
    return self.hydrate_path(*fields)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/py2neo/internal/hydration/__init__.py", line 274, in hydrate_path
    return Path(*steps)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/py2neo/data.py", line 1078, in __init__
    Walkable.__init__(self, walk(*entities))
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/py2neo/data.py", line 669, in __init__
    self.__sequence = tuple(iterable)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/py2neo/data.py", line 59, in walk
    raise ValueError("Cannot append walkable %r "
ValueError: Cannot append walkable (COMP00477.TESTLAB.LOCAL)-[:HasSession {}]->(PLONGLEY00240@TESTLAB.LOCAL) to node (_191:Computer {domain: 'TESTLAB.LOCAL', name: 'COMP00161.TESTLAB.LOCAL', owned: false})
Scoubi 04:08
COMP00161.TESTLAB.LOCAL is referenced in path #23
COMP00477.TESTLAB.LOCAL)-[:HasSession {}]->(PLONGLEY00240@TESTLAB.LOCAL is in path #8
I'm really lost..

```
